- hosts: webservers
  remote_user: danny
  vars:
    nginx_port: 80
  tasks: 
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: latest
    become: yes

  - name: copy page
    ansible.builtin.template:
      src: files/index.html
      dest: /usr/share/nginx/html/index.html
    become: yes
    notify: 
      - restart nginx

  - name: copy nginx cfg
    ansible.builtin.template:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
    become: yes
    notify:
      - restart nginx

  handlers: 
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: reloaded
    become: yes
