- hosts: webservers
  remote_user: danny
  tasks:
  - name: install git 
    ansible.builtin.apt:
      state: present
      name:
        - make
        - git
        - nodejs
    become: yes

  - name: create users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop:
      - tiron
      - arya
      - sansa
    become: yes

  - name: Paste git configs 
    ansible.builtin.template:
      src: files/.gitconfig
      dest: "/home/{{ item }}/.gitconfig"
    loop: 
      - tiron
      - arya
      - sansa
    become: yes

  - name: Create ssh directory
    file:
      path: "/home/{{ item }}/.ssh"
      state: directory
    loop:
      - tiron
      - arya
      - sansa
    become: yes

  - name: Copy public ssh key
    ansible.builtin.copy:
      src: /home/main/.ssh/id_rsa.pub
      dest: "/home/{{ item }}/.ssh/authorized_keys"
    loop: 
      - tiron
      - arya
      - sansa
    become: yes 
