- hosts: webservers
  remote_user: danny
  vars:
    users:
      - tiron
      - arya
      - sansa
  tasks:
  - name: install git 
    ansible.builtin.apt:
      state: present
      name:
        - make
        - git
        - nodejs
    become: yes

  - name: create users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop: '{{ users }}'
    become: yes

  - name: Paste git configs 
    ansible.builtin.template:
      src: files/.gitconfig
      dest: "/home/{{ item }}/.gitconfig"
    loop: '{{ users }}'
    become: yes

  - name: Add public keys
    ansible.posix.authorized_key:
      user: '{{ item }}'
      state: present
      key: "{{ lookup('file', '/home/main/.ssh/id_rsa.pub') }}"
    become: yes
    loop: '{{ users }}' 
